image: ubuntu:latest

.test_job_template: &test_job_definition
  script:
    - emacs --version
    - make ci-dependencies
    - make check

test:emacs:25.1:
  image: silex/emacs:25.1-dev
  <<: *test_job_definition

test:emacs:25.3:
  image: silex/emacs:25.3-dev
  <<: *test_job_definition

test:emacs:26:
  image: silex/emacs:26-dev
  <<: *test_job_definition
